name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: library-app
          path: target/*.jar

      - name: Build Docker image
        run: docker build -t library-app .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag library-app ${{ secrets.DOCKER_HUB_USERNAME }}/library-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/library-app:latest