name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kód
        uses: actions/checkout@v4

      - name: Java 21 beállítása
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven függőségek letöltése
        run: mvn dependency:resolve

      - name: Unit tesztek futtatása
        run: mvn clean test

      - name: JaCoCo teszt jelentés generálása
        run: mvn jacoco:report

      - name: Alkalmazás buildálása
        run: mvn clean package -DskipTests

      - name: Teszt eredmények publikálása
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit

      - name: Teszt jelentések mentése
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/site/jacoco/
            target/*.jar